[package]
name = "pigment64"
version = "0.3.0"
edition = "2021"
description = "A library for handling conversion between N64 texture formats and modern image formats"
repository = "https://github.com/decompals/pigment64"
license = "MIT"

[dependencies]
png = "0.17.9"
clap = { version = "4.3.17", features = ["derive"] }
anyhow = "1.0.72"
byteorder = "1.4.3"
num_enum = "0.6.1"
